version: '3'

services:
    diaryapp:
        build: .
        restart: always
        ports:
            - "80:80"
        environment:
            - "ASPNETCORE_ENVIRONMENT=Production"
        volumes:
            - "./data:/app/AppData"
